# Generated by Django 5.1.1 on 2024-12-23 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_level_code', models.CharField(max_length=10)),
                ('courselevel_name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(max_length=10, unique=True)),
                ('department_name', models.CharField(max_length=50, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('marital_status', models.CharField(max_length=50)),
                ('mobile_no', models.PositiveIntegerField()),
                ('religion', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('subcounty', models.CharField(max_length=50)),
                ('permanent_address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('town', models.CharField(max_length=50)),
                ('kin_relationship', models.CharField(max_length=50)),
                ('kin_firstname', models.CharField(max_length=50)),
                ('kin_lastname', models.CharField(max_length=50)),
                ('kin_address', models.CharField(max_length=255)),
                ('kin_town', models.CharField(max_length=50)),
                ('kin_contact', models.IntegerField()),
                ('kin_email', models.EmailField(max_length=254)),
                ('learning_mode', models.CharField(max_length=30)),
                ('preferred_semester', models.CharField(max_length=50)),
                ('schools_attended', models.TextField(max_length=255)),
                ('financing', models.CharField(max_length=50)),
                ('preferred_campus', models.CharField(max_length=50)),
                ('need_accommodation', models.CharField(max_length=50)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('uploadcertificates', models.FileField(blank=True, null=True, upload_to='mediafiles')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to=settings.AUTH_USER_MODEL)),
                ('course_level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equatorcollege.courselevel')),
                ('course_name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equatorcollege.coursename')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equatorcollege.department')),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_admission', models.CharField(blank=True, max_length=30)),
                ('approve', models.CharField(max_length=30)),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('approval_date', models.DateTimeField(auto_now_add=True)),
                ('is_unit_registered', models.BooleanField(default=False)),
                ('is_mark_added', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='equatorcollege.studentinformation')),
            ],
        ),
        migrations.CreateModel(
            name='UnitRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(blank=True)),
                ('unit_code', models.CharField(max_length=20)),
                ('unit_name', models.CharField(max_length=50)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_mark_added', models.BooleanField(default=False)),
                ('approved_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equatorcollege.studentapproval')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usertype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=20)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
