# Generated by Django 5.1.1 on 2024-11-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equatorcollege', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapproval',
            name='assign_admission',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
