# Generated by Django 5.1.1 on 2024-11-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equatorcollege', '0002_alter_studentapproval_assign_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitregistration',
            name='term',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
